### ISSUE TITLE
Error: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by lishen** [Magdoll/cDNA_Cupcake#20] opened 2017-09-28 14:43 UTC
This is the command I used:
`collapse_isoforms_by_sam.py --input $FASTQ --fq 
    -s $SORTED_SAM 
    -o ${OUT_DIR}/25675.polished_high_qv_consensus_isoforms_collapsed
`

The program ran for a while and I got the following error:

> Traceback (most recent call last):
  File "/home/shenl03/anaconda2/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==3.7', 'collapse_isoforms_by_sam.py')
  File "/home/shenl03/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/shenl03/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/data/home/shenl03/anaconda2/lib/python2.7/site-packages/cupcake-3.7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 244, in <module>
    main(args)
  File "/data/home/shenl03/anaconda2/lib/python2.7/site-packages/cupcake-3.7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 190, in main
    for recs in iter:
  File "/home/shenl03/anaconda2/lib/python2.7/site-packages/cupcake-3.7-py2.7-linux-x86_64.egg/cupcake/tofu/branch/branch_simple2.py", line 81, in iter_gmap_sam
    ignored_fout.write("{0}\tCoverage {1:.3f} too low.\n".format(r.qID, r.qCoverage))
ValueError: Unknown format code 'f' for object of type 'str'

Please offer a fix!

**Comment by Magdoll** [comment] 2017-09-28 15:17
Hi @lishen,
This error is almost always caused by one of two things:

1. the SAM file was not sorted properly. The sort command should be:
```
sort -k 3,3 -k 4,4n input.sam > input.sorted.sam
```

2. The SAM file contains incomplete alignments. This is usually discovered via running the aligner (GMAP, STAR, etc) again and ensuring that the process finished. 

If neither fixes the problem, I would need to take a look at the SAM file to know the cause.

Thanks,
--Liz

**Comment by lishen** [comment] 2017-09-28 16:12
@Magdoll ,

I converted sam to bam and sorted them using samtools and convert back to sam. I'm sure the sam files are already sorted.

But what do you mean by incomplete alignments? There are unmapped reads, which are at the tail of a sam file with a tag value of 4. Are they the reads that are causing trouble?

**Comment by Magdoll** [comment] 2017-09-28 18:16
Hi @lishen,

Sorting using samtools has been known to cause this error. Can you please try:

```
sort -k 3,3 -k 4,4n input.sam > input.sorted.sam
```

and see if this problem goes away? Alternatively, you can remove all alignments that are unmapped. 

The error shows up because it is expecting all unmapped alignments to either not exist at all, or appear all at the beginning of the SAM file. It's trying to print "r.qCoverage" for an alignment that is unmapped and since it's unmapped r.qCoverage is not a number.

--Liz

**Comment by Magdoll** [comment] 2018-03-09 16:48
Closing issue unless noted otherwise.

**Closed by Magdoll** 2018-03-09 16:48 UTC

**Comment by rlittman16** [comment] 2019-05-16 20:32
I was using samtools sort, and got this error then I used:
 `sort -k 3,3 -k 4,4n input.sam > input.sorted.sam` 
I have the same error.
